// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250211195636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 610, DateTimeKind.Local).AddTicks(2303),
                            Email = "User1@gmail.com",
                            Name = "User1",
                            Password = "$2a$11$PGNe75/FVzsbmmoCuyuV7.4tSiz7mKndNChj.w7VVJqeiu3ukBR4a",
                            UpdatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 610, DateTimeKind.Local).AddTicks(2315)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 744, DateTimeKind.Local).AddTicks(3460),
                            Email = "User2@gmail.com",
                            Name = "User2",
                            Password = "$2a$11$0QOMXvY.JrUlDKbYwOGjDOGoJTnBe4BDXDB/HysJiToO6JiP7qwY2",
                            UpdatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 744, DateTimeKind.Local).AddTicks(3479)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("734eb585-e9f1-44c9-ab05-7e9af8273bb6"),
                            CreatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 896, DateTimeKind.Local).AddTicks(9706),
                            Description = "Description1",
                            ImageUrl = "Image1",
                            Name = "Product1",
                            UpdatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 896, DateTimeKind.Local).AddTicks(9707)
                        },
                        new
                        {
                            Id = new Guid("48d304ba-af40-4ee8-b4c7-031fd9a5a6c6"),
                            CreatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 896, DateTimeKind.Local).AddTicks(9712),
                            Description = "Description2",
                            ImageUrl = "Image2",
                            Name = "Product2",
                            UpdatedDate = new DateTime(2025, 2, 12, 2, 56, 35, 896, DateTimeKind.Local).AddTicks(9713)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
